### ISSUE TITLE
Crash if typing wrong ID

### ISSUE THREAD

**Issue by SebastianSava** [55sketch/gsx2json#15]
Can you check: http://gsx2json.com/api?id=1ooDU8C_EWQ-wkx7PTWyknLd87o3vqTS9T78WEtFPmqg

**Comment by 55sketch** [comment]
I believe this is because the spreadsheet has not been published. If I visit the Google sheets JSON URL directly I get this message:
https://spreadsheets.google.com/feeds/list/1ooDU8C_EWQ-wkx7PTWyknLd87o3vqTS9T78WEtFPmqg/1/public/values?alt=json

![image](https://user-images.githubusercontent.com/7382191/107873829-59356080-6ead-11eb-8bfe-6b95629c7050.png)

I will raise a fix to handle this in future so that the app does not crash but for now if you publish the sheet as per the instructions on GSX2JSON.com then it should work for you.
